sudo: required
dist: bionic
language: python

branches:
  except:
    - dev
    - docker-integration
    - docker-test

env:
  global:
    - ANDROID_SDK=6858069
    - BAZEL=3.7.2

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.6
    - os: osx
      osx_image: xcode11.3
      language: cpp
  allow_failures:
    - os: osx
      osx_image: xcode11.3
      language: cpp

before_install:
  - . travis/before_install.sh

install:
  - yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" 'build-tools;28.0.3' 'platforms;android-28' > /dev/null
  - pip3 install -r travis/requirements.txt

script:
  - travis/script.sh
